- app/build.gradle.kts
- build.gradle.kts
- core-database/build.gradle.kts
- core-database/src/main/java/com/hmoa/core_database/DataStoreModule.kt
- core-database/src/main/java/com/hmoa/core_database/TokenManagerImpl.kt
- core-datastore/build.gradle.kts
- core-datastore/src/main/java/com/hmoa/core_datastore/TokenManagerModule.kt
- core-network/build.gradle.kts
- core-network/src/main/java/com/hmoa/core_network/AuthenticatorModule.kt
- core-network/src/main/java/com/hmoa/core_network/HttpClientModule.kt
- core-network/src/main/java/com/hmoa/core_network/authentication/AuthenticatorImpl.kt
- core-repository/build.gradle.kts
- core-repository/src/main/java/com/hmoa/core_repository/Community/CommunityRepositoryImpl.kt
- core-repository/src/main/java/com/hmoa/core_repository/CommunityComment/CommunityCommentRepositoryImpl.kt
- core-repository/src/main/java/com/hmoa/core_repository/PerfumeComment/PerfumeCommentRepositoryImpl.kt
- core-repository/src/main/java/com/hmoa/core_repository/Perfumer/PerfumerRepositoryImpl.kt
- core-repository/src/main/java/com/hmoa/core_repository/RepositoryModule.kt
- feature-authentication/build.gradle.kts
- feature-authentication/src/main/java/com/hmoa/feature_authentication/LoginScreen.kt
repository 객체 주입하는 모듈 추가해서 data계층에 전체적인 hilt 적용은 완료된 상태입니다
project 수준의 gradle에서 kotlin 플러그인 없는 게 문제가 되어서 추가하고
hilt 버전도 app수준, project 수준 모두 2.44 -> 2.48.1 로 업그레이드 했습니다
interceptor에서 TokenManager, LoginService를 주입하고 참조하는 과정에서 순환오류가 생긴 것 같고
ktor+hilt적용 레퍼런스가 부족해서 약간 혼란을 겪고 있는데 토욜까지 진척이 없으면 retrofit2로 교체해서 올리겠습니다!
> Feature/hilt fix Hilt 버전 및 외부 모듈 주입 변경

- core-datastore/src/main/java/com/hmoa/core_datastore/Member/MemberDataStoreImpl.kt
- core-domain/src/main/java/com/hmoa/core_domain/usecase/GetMyCommentUseCase.kt
- core-domain/src/main/java/com/hmoa/core_domain/usecase/GetMyFavoriteCommentUseCase.kt
- core-domain/src/main/java/com/hmoa/core_domain/usecase/GetMyUserInfoUseCase.kt
- core-network/src/main/java/com/hmoa/core_network/service/Member/MemberService.kt
- core-network/src/main/java/com/hmoa/core_network/service/Member/MemberServiceImpl.kt
> Core/useCase 키워드 수정

- core-domain/src/main/java/com/hmoa/core_domain/repository/MemberRepository.kt
- core-domain/src/main/java/com/hmoa/core_domain/usecase/GetMyCommentByPerfumeUseCase.kt
- core-domain/src/main/java/com/hmoa/core_domain/usecase/GetMyCommentByPostUseCase.kt
- core-domain/src/main/java/com/hmoa/core_domain/usecase/GetMyFavoriteCommentByPerfumeUseCase.kt
- core-domain/src/main/java/com/hmoa/core_domain/usecase/GetMyFavoriteCommentByPostUseCase.kt
- core-domain/src/main/java/com/hmoa/core_domain/usecase/GetMyFavoriteCommentUseCase.kt
- core-domain/src/main/java/com/hmoa/core_domain/usecase/GetMyPostUseCase.kt
- core-model/src/main/java/com/hmoa/core_model/response/CommunityByCategoryResponseDto.kt
- core-network/src/main/java/com/hmoa/core_network/service/Member/MemberService.kt
- core-network/src/main/java/com/hmoa/core_network/service/Member/MemberServiceImpl.kt
각 기능에 대한 Use Case 작업해서 PL 날립니다!
기본적인 구조만 잡고 View Model 연결하면서 Test 해보겠습니다!
> Core/useCase UseCase 완료

- feature-userInfo/build.gradle.kts
- feature-userInfo/src/main/java/com/hmoa/feature_userinfo/MyCommentPage.kt
- feature-userInfo/src/main/java/com/hmoa/feature_userinfo/viewModel/FavoriteCommentViewModel.kt
- feature-userInfo/src/main/java/com/hmoa/feature_userinfo/viewModel/PostViewModel.kt
ViewModel 상속이 안 된채로 Viewmodel 클래스가 있더라구요?! 그 부분 수정하고,
feature-userInfo 모듈 만들때 build.gradle.kts 아이디가 잘못돼서 수정했습니다!
when()구문 쓰신 부분 빈 else구문 추가해서 일단 빌드만 되게 했습니다. 자세한 건 커밋 참고해주세요!
> Feature/data 빌드문제 수정

- core-designsystem/build.gradle.kts
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/Comment.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/PostListItem.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/TypeButton.kt
- core-designsystem/src/main/res/drawable/badge.xml
- core-designsystem/src/main/res/drawable/three_dot_menu.xml
서버로부터 받는 이미지 url을 띄울 Coil 라이브러리를 추가했습니다
선택된 게시글 유형을 나타낼 Component 추가했습니다
> Feature/component 컴포넌트 추가 및 Coil 라이브러리 추가

- app/build.gradle.kts
- core-common/build.gradle.kts
- core-database/build.gradle.kts
- core-datastore/build.gradle.kts
- core-datastore/src/main/java/com/hmoa/core_datastore/DatastoreModule.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/PerfumeComment/PerfumeCommentDataStoreImpl.kt
- core-designsystem/build.gradle.kts
- core-domain/build.gradle.kts
- core-model/src/main/java/com/hmoa/core_model/data/UserInfo.kt
- core-network/build.gradle.kts
- core-network/src/main/java/com/hmoa/core_network/di/ServiceModule.kt
- core-repository/build.gradle.kts
- core-repository/src/main/java/com/hmoa/core_repository/RepositoryModule.kt
- feature-authentication/build.gradle.kts
- feature-perfume/build.gradle.kts
- feature-userInfo/build.gradle.kts
- sample-app/build.gradle.kts
지난번에 ktor->retrofit2로 변경하면서 급하게 수정된 것들 중에 누락된 hilt 주입 객체들이 있어서 수정했습니다!
sdk버전은 모두 26으로 올렸고 빌드 성공 확인했습니다!
> Master hilt빌드 오류 수정 및 sdk 버전 업그레이드

- core-datastore/src/main/java/com/hmoa/core_datastore/Community/CommunityDataStore.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/Community/CommunityDataStoreImpl.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/CommunityComment/CommunityCommentDataStore.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/CommunityComment/CommunityCommentDataStoreImpl.kt
- core-domain/src/main/java/com/hmoa/core_domain/repository/CommunityCommentRepository.kt
- core-domain/src/main/java/com/hmoa/core_domain/repository/CommunityRepository.kt
- core-network/src/main/java/com/hmoa/core_network/service/CommunityCommentService.kt
- core-network/src/main/java/com/hmoa/core_network/service/CommunityService.kt
- core-repository/src/main/java/com/hmoa/core_repository/CommunityCommentRepositoryImpl.kt
- core-repository/src/main/java/com/hmoa/core_repository/CommunityRepositoryImpl.kt
- feature-community/src/main/java/com/hmoa/feature_community/ViewModel/CommunityDescViewModel.kt
- feature-community/src/main/java/com/hmoa/feature_community/ViewModel/CommunityEditViewModel.kt
- feature-community/src/main/java/com/hmoa/feature_community/ViewModel/CommunityHomeViewModel.kt
- feature-community/src/main/java/com/hmoa/feature_community/ViewModel/CommunityMainViewModel.kt
- feature-community/src/main/java/com/hmoa/feature_community/ViewModel/CommunityPostViewModel.kt
Community, CommunityComment의 경우 ApiResult와 ResultResponse로 모두 처리했습니다!
이번주 회의 때 에러 처리를 사용자에게 어떤 식으로 전달할지 얘기해볼까용?
> Feature/community ApiResult, ResultResponse로 Wrapping

- core-designsystem/src/main/java/com/hmoa/core_designsystem/BottomNavItem.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/BottomScreen.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/MainBottomBar.kt
BottomScreen Enum Class 생성 후 적용했습니다.
BottomNavigationItem에서 name 대신 BottomScreen 클래스를 사용하도록 변경한 후 PR 합니다!
> Feature/component Main Bottom Bar

- app/src/main/java/com/hmoa/app/MainScreen.kt
- core-domain/src/main/java/com/hmoa/core_domain/repository/LoginRepository.kt
- core-domain/src/main/java/com/hmoa/core_domain/usecase/PostKakaoTokenUseCase.kt
- core-domain/src/main/java/com/hmoa/core_domain/usecase/PostSignupUseCase.kt
- core-repository/src/main/java/com/hmoa/core_repository/LoginRepositoryImpl.kt
- feature-authentication/src/main/java/com/hmoa/feature_authentication/viewmodel/LoginViewModel.kt
> Fix: 누락 수정

- app/src/main/java/com/hmoa/app/navigation/NavHost.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/TopBarWithEvent.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/navigation/PerfumeRoute.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/navigation/perfumeNavigation.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/screen/CreateNewPerfumeCommentScreen.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/screen/PerfumeCommentScreen.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/screen/PerfumeScreen.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/viewmodel/CreateNewPerfumeViewmodel.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/viewmodel/EditMyPerfumeCommentViewmodel.kt
https://github.com/HMOAA/HMOA_ANDROID/pull/59 이후로 토큰 값이 안나오는 현상 때문에 해당 기능 테스트 및 확인은 안됐습니다.
swagger상에는 향수단건 조회는 토큰이 필요한 요청이라고 나오지만 알고보니 토큰이 없어도 요청가능한 api여서 늦게 확인하게 됐습니다. 토큰 부분은 다시 수정해서 올리겠습니다!😭
> Feature/perfume 댓글추가페이지, 댓글수정페이지 생성

- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/SearchTopBar.kt
제가 생각한대로 Component를 만들어 뒀습니다!
feat. figma에서 확인해보니 검색할 내용이 들어가면 search icon이 delete icon으로 변경되는 것으로 보여서요! 제 생각에는 search icon은 그대로 있고 delete icon이 생기는 게 편하지 않을까 했는데 어떻게 생각하시나요?
용인님 의견듣고 맞춰서 수정하고 제가 Merge 하도록 하겠습니당!
> Feat: 검색 Top Bar 추가

- app/src/main/java/com/hmoa/app/MainActivity.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/Comment.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/CommentItem.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/TopBar.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/theme/CustomColor.kt
- core-model/src/main/java/com/hmoa/core_model/data/ErrorMessage.kt
- feature-community/src/main/java/com/hmoa/feature_community/Screen/CommunityEditPage.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/screen/CreateNewPerfumeCommentScreen.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/screen/EditMyPerfumeCommentScreen.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/screen/PerfumeScreen.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/screen/SpecificCommentScreen.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/viewmodel/PerfumeCommentViewmodel.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/viewmodel/SpecificCommentViewmodel.kt
- feature-userInfo/src/main/java/com/hmoa/feature_userinfo/Screen/MyCommentPage.kt
- feature-userInfo/src/main/java/com/hmoa/feature_userinfo/Screen/MyFavoriteCommentPage.kt
얘기된 작업은 아니었지만 제가 맡은 부분 누락된 부분 수정 하다가 
userInfo 댓글 디자인 누락된 부분들이 보여서 수정했습니다!
> Detail 디자인 누락 수정

- app/src/main/java/com/hmoa/app/navigation/NavHost.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/Main/MainDataStore.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/Main/MainDataStoreImpl.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/AppDefaultDialog.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/AppLoadingScreen.kt
- core-domain/src/main/java/com/hmoa/core_domain/repository/MainRepository.kt
- core-network/src/main/java/com/hmoa/core_network/service/MainService.kt
- core-repository/src/main/java/com/hmoa/core_repository/MainRepositoryImpl.kt
- feature-home/src/main/java/com/hmoa/feature_home/navigation/HomeNavigation.kt
- feature-home/src/main/java/com/hmoa/feature_home/navigation/HomeRoute.kt
- feature-home/src/main/java/com/hmoa/feature_home/screen/AllPerfumeScreen.kt
- feature-home/src/main/java/com/hmoa/feature_home/screen/HomeScreen.kt
- feature-home/src/main/java/com/hmoa/feature_home/viewmodel/AllPerfumeViewModel.kt
- feature-home/src/main/java/com/hmoa/feature_home/viewmodel/HomeViewModel.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/viewmodel/PerfumeViewmodel.kt
홈 화면 향수들의 전체보기 페이지가 누락되어서 새로 생성했습니다
그외 로딩 추가, 컴포넌트 패딩 추가했습니다
> Detail  홈 향수 - 전체보기 페이지 생성

- app/build.gradle.kts
- build.gradle.kts
- feature-userInfo/src/main/java/com/hmoa/feature_userinfo/Screen/MyPage.kt
수정해서 완료했습니다.
관련 오픈소스 라이센스 다 나오도록 수정했고, 디자인 관련해서 바꾸는 것은 배경, 제목 등등 Theme.xml을 이용해서 변경은 가능합니다.
> Feature/fcm OSS 설정 완료

- feature-userInfo/build.gradle.kts
- feature-userInfo/src/main/java/com/hmoa/feature_userinfo/Screen/MyPage.kt
향모아 웹사이트에서 명시하는 개인정보처리 방침 노션페이지의 uri 추가했습니다!
> Feat: 개인정보처리 방침 추가

- app/src/main/java/com/hmoa/app/MainActivity.kt
- app/src/main/java/com/hmoa/app/navigation/NavHost.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/ErrorUiSetView.kt
- core-network/src/main/java/com/hmoa/core_network/di/ServiceModule.kt
- core-repository/src/main/java/com/hmoa/core_repository/FcmRepositoryImpl.kt
- feature-authentication/.gitignore
- feature-community/src/main/java/com/hmoa/feature_community/Navigation/NavGraph.kt
- feature-community/src/main/java/com/hmoa/feature_community/Screen/CommunityDescriptionPage.kt
- feature-community/src/main/java/com/hmoa/feature_community/Screen/CommunityHome.kt
- feature-community/src/main/java/com/hmoa/feature_community/Screen/CommunityPage.kt
- feature-community/src/main/java/com/hmoa/feature_community/ViewModel/CommunityDescViewModel.kt
- feature-community/src/main/java/com/hmoa/feature_community/ViewModel/CommunityEditViewModel.kt
- feature-community/src/main/java/com/hmoa/feature_community/ViewModel/CommunityHomeViewModel.kt
- feature-community/src/main/java/com/hmoa/feature_community/ViewModel/CommunityMainViewModel.kt
- feature-hpedia/src/main/java/com/hmoa/feature_hpedia/Navigation/NavGraph.kt
- feature-hpedia/src/main/java/com/hmoa/feature_hpedia/Screen/HPediaScreen.kt
- feature-hpedia/src/main/java/com/hmoa/feature_hpedia/Screen/HpediaSearchScreen.kt
- feature-like/src/main/java/com/hmoa/feature_like/Screen/LikeScreen.kt
- feature-like/src/main/java/com/hmoa/feature_like/ViewModel/LikeViewModel.kt
- feature-userInfo/src/main/java/com/hmoa/feature_userinfo/viewModel/MyPageViewModel.kt
토큰 없을 때 FCM을 보내어 오류가 발생하는 것을 방지했습니다
UserInfo 모듈 (MyPage), Like 모듈(Like Page), Community 모듈(Community Description Page) 에서 각각 에러 처리를 통해 토큰 없이 api를 호출하는 것을 막았습니다
> Fix/fcm : Fcm 관련 오류 및 Error 처리 추가

- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/ErrorUiSetView.kt
- core-domain/src/main/java/com/hmoa/core_domain/usecase/GetPerfumeUsecase.kt
- core-model/src/main/java/com/hmoa/core_model/data/Perfume.kt
- feature-community/src/main/java/com/hmoa/feature_community/Screen/CommunityDescriptionPage.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/screen/PerfumeCommentScreen.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/screen/PerfumeScreen.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/viewmodel/PerfumeCommentViewmodel.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/viewmodel/PerfumeViewmodel.kt
논리적으로 많은 변화가 없어서 일찍 끝났습니다! 이제 배포만 하면 되네요!
> HMOA-80--DTO-Model- 향수 dto 수정사항 반영

- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/ErrorUiSetView.kt
- feature-community/src/main/java/com/hmoa/feature_community/Screen/CommunityDescriptionPage.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/screen/PerfumeCommentScreen.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/screen/PerfumeScreen.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/viewmodel/PerfumeCommentViewmodel.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/viewmodel/PerfumeViewmodel.kt
향수 상세 페이지, 향수 댓글 상세 페이지에 비로그인 에러 다이얼로그 추가했습니다.
> Hmoa 28  unlogined user 누락 추가

- .idea/gradle.xml
- app/.gitignore
- app/build.gradle.kts
app모듈에 OssLicense 관련 라이브러리 의존성이 누락돼어서 추가하고
여기까지의 개발 버전으로  릴리즈 aab 생성해서 구글 제출할 예정입니다
> 1.0.0build 빌드 오류 수정 및 최종 aab 파일 빌드

- app/build.gradle.kts
- feature-perfume/src/main/java/com/hmoa/feature_perfume/viewmodel/PerfumeCommentViewmodel.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/viewmodel/PerfumeViewmodel.kt
향수페이지와 관련된 viewmodel에서 hasToken 변수 초기화가 잘못 되어있어서 수정했습니다
> Hmoa 104 비로그인 에러다이얼 로그 버그 수정

- app/.gitignore
- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/hmoa/app/MainActivity.kt
- core-database/src/main/java/com/hmoa/core_database/TokenManager.kt
- core-database/src/main/java/com/hmoa/core_database/TokenManagerImpl.kt
- core-network/src/main/java/com/hmoa/core_network/authentication/AuthAuthenticator.kt
- core-network/src/main/java/com/hmoa/core_network/di/ServiceModule.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/viewmodel/PerfumeViewmodel.kt
오류가 날 때 튕기는 줄 알았는데 가만히 있어도 튕길 때가 있었습니다. 토큰 추가는 비동기고 인터셉터에서 요청 생성하는 건 동기라서 타이밍이 어긋나면 스트림에 2번 이상 접근하게 되는 것 같아서 토큰 추가 동작을 TokenManager 함수를 분리해서 동기적으로 동작하도록 해보았습니다.
```kotlin
Exception java.lang.IllegalStateException: closed
at okio.RealBufferedSource.request (RealBufferedSource.kt:207)
at okhttp3.logging.HttpLoggingInterceptor.intercept (HttpLoggingInterceptor.kt:247)
at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
at com.hmoa.core_network.di.ServiceModule.provideHeaderInterceptor$lambda$1 (ServiceModule.kt:87)
at com.hmoa.core_network.di.ServiceModule.$r8$lambda$MSkSlZfKxfCZpWG5iUZTSMr7WDs
at com.hmoa.core_network.di.ServiceModule$$ExternalSyntheticLambda0.intercept
at okhttp3.internal.http.RealInterceptorChain.proceed …
```
> Feature/after anr solve v1.0.0(7) ANR 오류 수정

- core-model/src/main/java/com/hmoa/core_model/response/PerfumerDefaultResponseDto.kt
- feature-hpedia/src/main/java/com/hmoa/feature_hpedia/Screen/HpediaSearchScreen.kt
HPedia 문제 없이 3개 다 처리되는 것으로 확인했습니다!
> Fix: 변수 명 오류

- app/build.gradle.kts
> Release v1.0.0(11)

- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/AlarmItem.kt
> Feature/component 알림 목록 관련 컴포넌트 추가

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/hmoa/app/AppViewModel.kt
- app/src/main/java/com/hmoa/app/FcmAppService.kt
- app/src/main/java/com/hmoa/app/MainActivity.kt
- app/src/main/java/com/hmoa/app/navigation/NavHost.kt
- core-database/src/main/java/com/hmoa/core_database/AppInfoManagerImpl.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/Fcm/FcmRemoteDataStore.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/Fcm/FcmRemoteDataStoreImpl.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/AlarmItem.kt
- core-domain/src/main/java/com/hmoa/core_domain/repository/FcmRepository.kt
- core-model/src/main/java/com/hmoa/core_model/response/AlarmResponse.kt
- core-network/src/main/java/com/hmoa/core_network/service/FcmService.kt
- core-repository/src/main/java/com/hmoa/core_repository/FcmRepositoryImpl.kt
- feature-community/src/main/java/com/hmoa/feature_community/Navigation/NavGraph.kt
- feature-community/src/main/java/com/hmoa/feature_community/ViewModel/CommunityDescViewModel.kt
- feature-fcm/build.gradle.kts
- feature-fcm/src/main/java/com/hmoa/feature_fcm/AlarmNavigation.kt
- feature-fcm/src/main/java/com/hmoa/feature_fcm/AlarmScreen.kt
- feature-fcm/src/main/java/com/hmoa/feature_fcm/AlarmViewModel.kt
- feature-fcm/src/test/java/com/hmoa/feature_fcm/ExampleUnitTest.kt
- feature-fcm/src/test/java/com/hmoa/feature_fcm/TestFcmRepository.kt
- feature-hpedia/src/main/java/com/hmoa/feature_hpedia/Navigation/NavGraph.kt
- feature-perfume/src/main/java/com/hmoa/feature_perfume/navigation/perfumeNavigation.kt
Main Activity에서 권한을 허용할 경우 >> fcm token 발송 및 저장
Main Activity에서 권한을 허용하지 않는 경우 >> fcm token 삭제
앱 권한 설정을 밖에서 변경한 경우 >> 앱에 들어오면서 확인하게 되어 fcm token을 사용할지 말지 선택 가능
deep link 설정하는 게 맞는 지는 모르겠으나 현재 intent를 통해 받은 deeplink의 host로 구분지어서 navigation 하는 방법으로 구현했습니다.
feat. user info 모듈에 알림 버튼 iOS 사진 주시면 그거보고 대강 만들어서 기능 구현 먼저 해볼게요! 디자인은 나중에 바꿀게용
> Feature/fcm : FCM 설정

- app/src/main/java/com/hmoa/app/navigation/NavHost.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/DatastoreModule.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/Survey/SurveyDataStore.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/Survey/SurveyDataStoreImpl.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/SurveyOptionList.kt
- core-domain/src/main/java/com/hmoa/core_domain/repository/SurveyRepository.kt
- core-model/src/main/java/com/hmoa/core_model/request/NoteResponseDto.kt
- core-model/src/main/java/com/hmoa/core_model/request/SurveyRespondRequestDto.kt
- core-model/src/main/java/com/hmoa/core_model/response/RecommendNotesResponseDto.kt
- core-model/src/main/java/com/hmoa/core_model/response/SurveyAnswerResponseDto.kt
- core-model/src/main/java/com/hmoa/core_model/response/SurveyOptionResponseDto.kt
- core-model/src/main/java/com/hmoa/core_model/response/SurveyQuestionResponseDto.kt
- core-model/src/main/java/com/hmoa/core_model/response/SurveyQuestionsResponseDto.kt
- core-network/src/main/java/com/hmoa/core_network/di/ServiceModule.kt
- core-network/src/main/java/com/hmoa/core_network/service/SurveyService.kt
- core-repository/src/main/java/com/hmoa/core_repository/RepositoryModule.kt
- core-repository/src/main/java/com/hmoa/core_repository/SurveyRepositoryImpl.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/navigation/HbtiNavigation.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/navigation/HbtiRoute.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/HbtiScreen.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/HbtiSurveyScreen.kt
viewmodel 상태관리나 함수호출 순서 관련해서 테스트코드 작성해보려고 하고 있습니당
core-designSystem의 프로그래스바가 있습니다. 디자인은 별거 없고 기능 예시를  Preview에 자세히 작성해보았습니다!
> Feature/hbti lyi, feature-hbti 모듈 작업

- app/src/main/java/com/hmoa/app/navigation/NavHost.kt
- core-model/src/main/java/com/hmoa/core_model/data/NoteSelect.kt
- core-network/src/main/java/com/hmoa/core_network/service/HshopService.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/navigation/HbtiNavigation.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/HbtiSurveyResultScreen.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/NotePickScreen.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/viewmodel/NotePickViewmodel.kt
향료 선택 결과 api 추가하고 빠진 부분들 수정했습니다!
NotePickScreen에서부터 이어서 작업하시면 될 거 같습니다
향료 선택 인덱싱오류가 있는데 아직 수정을 다시 해야해서 디바이스 테스트하시면 읭 스러울 수 있습니다.😭 하지만 작업 이어나가시는데는 문제없을 거 같아서 우선 PR합니다.
> Feature/hbti lyi 향료 선택 결과 제출 api 추가

- app/build.gradle.kts
- feature-community/src/main/java/com/hmoa/feature_community/ViewModel/CommunityHomeViewModel.kt
마이페이지 화면 외에 커뮤니티 홈화면에도 필요한데 누락되어서 추가 후 재제출 했습니다
8/8(목)에 리젝당한 버전이 이 버전입니다
바로 이 버전에서 버전코드만 17로 업데이트 해서 aar 돌려보겠습니다
> Hotfix/error message2 MemberNotFound 에러처리 누락화면 수정

- .idea/androidTestResultsUserPreferences.xml
- app/src/main/java/com/hmoa/app/navigation/NavHost.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/ErrorUiSetView.kt
- core-model/src/main/java/com/hmoa/core_model/data/NoteSelect.kt
- feature-hbti/src/androidTest/java/com/hmoa/feature_hbti/HbtiSurveyScreenTest.kt
- feature-hbti/src/androidTest/java/com/hmoa/feature_hbti/NotePickScreenTest.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/NoteOrderQuantity.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/navigation/HbtiNavigation.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/navigation/HbtiRoute.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/HbtiSurveyLoadingScreen.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/HbtiSurveyResultScreen.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/HbtiSurveyScreen.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/NoteOrderQuantityPickScreen.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/NotePickScreen.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/viewmodel/HbtiSurveyLoadingViewmodel.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/viewmodel/NoteOrderQuantityPickViewmodel.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/viewmodel/NotePickViewmodel.kt
- feature-hbti/src/test/java/com/hmoa/feature_hbti/HbtiSurveyViewModelTest.kt
- feature-hbti/src/test/java/com/hmoa/feature_hbti/NoteOrderQuantityPickViewmodelTest.kt
- feature-hbti/src/test/java/com/hmoa/feature_hbti/NotePickViewmodelTest.kt
HBTI 결과 로딩 화면을 컴포즈 함수로 해서 딜레이 시킨 후 렌더링하다가 RoomDB작업이랑 딜레이가 오류를 발생시켜서
독립적인 스크린과 뷰모델로 분리했습니다!
인덱싱이 꼬인 문제가 있었는데 리팩토링 완료되었습니다
최초 선택에는 문제없지만 백 화면을 이용해서 향료수량선택 화면으로 돌아와 재선택하는 경우에 튕기는 문제가 있어서 확인중입니다
> Feature/hbti lyi RoomDB 메인스레드 블로킹 오류 해결

- .github/workflows/android.yml
> Chore: CI 테스트 명령어 추가

- .github/workflows/android.yml
- app/build.gradle.kts
- copy-hmoa-android-secrets.sh
- core-database/src/main/java/com/hmoa/core_database/TokenManager.kt
- core-database/src/main/java/com/hmoa/core_database/TokenManagerImpl.kt
- core-network/src/main/java/com/hmoa/core_network/di/ServiceModule.kt
github action에 release, master 브랜치로 코드가 머지될 경우 apk추출이 되는 명령어도 테스트해 볼 겸 추가해보았습니다.
apk파일 추출 명령어를 어떤 브랜치에 적용할지 논의해보아도 좋을 거 같습니다
> Release review 1.0.0 (18) 버전

- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/SurveyOptionList.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/HbtiSurveyScreen.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/NoteOrderQuantityPickScreen.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/NotePickScreen.kt
1. Note Pick Screen 인덱스 오류
2. 설문 컴포넌트 단수/복수 프로퍼티 추가 및 UI내부 함수 추가
+ 호준 님도 가능하시다면 PR 많이 올려주세요!😇 
제가 최근까지 1차 명세 부분에서 자꾸 개발 흐름이 끊기는 오류를 많이 만든 거 같아서 답답하셨을 거 같습니다😭 
2차, 3차에서 다시 으쌰으쌰해봐요!!
> Feature/hbti lyi 1차 명세서 에러사항 수정

- core-database/src/main/java/com/hmoa/core_database/lrucache/CacheKey.kt
- core-database/src/main/java/com/hmoa/core_database/lrucache/PerfumeRecommendCacheManager.kt
- core-database/src/main/java/com/hmoa/core_database/lrucache/PerfumeRecommendCacheManagerImpl.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/Survey/SurveyLocalDataStore.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/Survey/SurveyLocalDataStoreImpl.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/Survey/SurveyRemoteDataStore.kt
- core-datastore/src/main/java/com/hmoa/core_datastore/Survey/SurveyRemoteDataStoreImpl.kt
- core-designsystem/src/main/java/com/hmoa/core_designsystem/component/LikeRowlistItem.kt
- core-domain/src/main/java/com/hmoa/core_domain/repository/SurveyRepository.kt
- core-model/src/main/java/com/hmoa/core_model/PerfumeRecommendType.kt
- core-network/src/main/java/com/hmoa/core_network/service/SurveyService.kt
- core-repository/src/main/java/com/hmoa/core_repository/SurveyRepositoryImpl.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/PerfumeRecommendationResultScreen.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/viewmodel/PerfumeRecommendationResultViewModel.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/viewmodel/PerfumeRecommendationViewModel.kt
- feature-hbti/src/test/java/com/hmoa/feature_hbti/PerfumeRecommendationViewmodelTest.kt
가격대 우선 / 향료 우선캐시 부분에 캐시를 적용한 방식으로 변경되었습니다\
로컬에서 develop브랜치로 코드푸시가 바로 되버려서 PR 필수인 걸로 바꿔놓았습니다!
> Feature/hbti lyi 향료추천 결과 화면 수정

- .github/workflows/cdWorkflow.yml
실수로 디벨롭 브랜치에 한번 코드를 푸시했더니 PR에 커밋들이 저 밑에 1개 밖에 없습니다...ㅎ
30분 마다 토큰을 리프레싱하는 임시방편으로 업데이트를 하게되었습니다.
리프레싱은 리멤버 토큰이 유효하기만 하면 확실히 되지만, 문제는 리프레싱이 실패한 경우 화면까지 전달이 안되었던 게 문제였던 거 같습니다 ㅠ
액세스 토큰 만료 -> 만료 오류는 "알 수 없는 오류"로 에러다이얼로그로 전달됨 -> 근데 리프레싱 실패 ->???여기서 끝
지난 회의때 에러상태랑 UI상태가 따로 놀아서 유기적으로 화면 업데이트가 안된다는 문제도 지적되었지만 이것도 근본적인 문제 중에 하나인 것 같아요..!
```kotlin
refreshTokenManager.refreshTokens(RememberedLoginRequestDto(rememberedToken))
.suspendOnError {
if (this.response.code() == 404) {
Log.e("AuthAuthenticator", "토큰 리프레싱 실패")
}
}
.suspendOnSuccess {
val responseBody = this.response.body()
if (responseBody != null) {
val refreshedAuthToken = responseBody.authToken
val refreshedRememberToken = responseBody.rememberedToken
launch {
tokenManager.deleteAuthToken() …
```
> 1.1.1 업데이트 사항

- .github/workflows/action.yml
> Fix: action.yml 추가

- .gitignore
- .idea/deploymentTargetSelector.xml
- .idea/other.xml
- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- core-common/src/main/java/com/hmoa/core_common/CommonFunctions.kt
- core-model/src/main/java/com/hmoa/core_model/response/HbtiHomeMetaDataResponse.kt
- core-network/src/main/java/com/hmoa/core_network/service/SurveyService.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/HbtiScreen.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/screen/HbtiSurveyScreen.kt
- feature-hbti/src/main/java/com/hmoa/feature_hbti/viewmodel/HbtiHomeViewModel.kt
- feature-home/src/main/java/com/hmoa/feature_home/screen/HomeScreen.kt
- 홈 화면 진입시 최상단 큰 그림 배너가 보이게 하는...기능입니다
- 1.0.0 버전 피드백에서 나왔던 건데 이제야 추가했습니다
> 향BTI 기능 누락 추가 및 피드백 반영
